### ISSUE TITLE
进游戏后还是不进荒原

### ISSUE THREAD

**Issue by dongwlin** [MaaAssistantArknights/MAA1999#10]
从这个界面启动后不进荒原，如果在主页会进荒原
![MuMu12-20230724-150529](https://github.com/MaaAssistantArknights/MAA1999/assets/97545700/cd856266-50ec-458b-b410-bfce1785fa4b)

这是log
[1.log](https://github.com/MaaAssistantArknights/MAA1999/files/12142632/1.log)

**Comment by MistEO** [comment]
v0.2.3 fixed
