### ISSUE TITLE
不领奖励

### ISSUE THREAD

**Issue by dongwlin** [MaaAssistantArknights/MAA1999#11]
没有进“任务”领奖励
就翻了两次邮箱就停了
这是log
[1.log](https://github.com/MaaAssistantArknights/MAA1999/files/12142656/1.log)
这是截图
![MuMu12-20230724-142833](https://github.com/MaaAssistantArknights/MAA1999/assets/97545700/7ef6f263-364f-4a92-a3b3-6a05c1259793)

**Comment by MistEO** [comment]
v0.2.3 fixed
