### ISSUE TITLE
满信赖时，会一直卡在收信赖

### ISSUE THREAD

**Issue by PieceOfFall** [MaaAssistantArknights/MAA1999#15]
##  如图所示，在荒岛收信赖时如果存在满信赖，则会一直卡在这里，因为满信赖max没法收取（确信
![image](https://github.com/MaaAssistantArknights/MAA1999/assets/85009059/db188f66-c1ae-4cab-9e79-c517548ce643)

**Comment by PieceOfFall** [comment]
因为荒原上放的是xp角色

**Comment by dongwlin** [comment]
不应该啊，看看log

**Comment by PieceOfFall** [comment]
[maa.log](https://github.com/MaaAssistantArknights/MAA1999/files/12224776/maa.log)

**Comment by PieceOfFall** [comment]
有设置超时时间处理吗，我看卡那里就退了

**Comment by dongwlin** [comment]
有信赖max识别，所以按理来说不会卡在这里，等会我看看log

**Comment by dongwlin** [comment]
懂力，深蓝又改东西了，岂可休！
