### ISSUE TITLE
failed to init Maa instance, connection error or resource file corruption occurred, please refer to the log

### ISSUE THREAD

**Issue by lolpbe** [MaaAssistantArknights/MAA1999#19]
![image](https://github.com/MaaAssistantArknights/MAA1999/assets/99073747/726f3da6-d89a-4d13-8306-2e344312cc5a)

**Comment by lolpbe** [comment]
[maa.log](https://github.com/MaaAssistantArknights/MAA1999/files/12428718/maa.log)

**Comment by lolpbe** [comment]
出现config后直接显示这个
![image](https://github.com/MaaAssistantArknights/MAA1999/assets/99073747/ab755919-f02b-40be-affc-6e447c7e0a8b)

**Comment by dongwlin** [comment]
adb连接出问题了，你检查一下你的adb路径或者模拟器的adb端口有没有写错
