### ISSUE TITLE
Bug: 不能正确启动B服

### ISSUE THREAD

**Issue by Trust04zh** [MaaAssistantArknights/MAA1999#32]
先在没有`config.json`时用cli跑了一次生成配置，再次使用cli的时候发现没有启动B服，遂看了下代码

https://github.com/MaaAssistantArknights/MAA1999/blob/eaa5397a746702acb4a96e5b4c3c958f65b4db7c/source/cli/main.cpp#L304

https://github.com/MaaAssistantArknights/MAA1999/blob/eaa5397a746702acb4a96e5b4c3c958f65b4db7c/source/cli/main.cpp#L476

读/写客户端类型的时候用的字段不一样，本地把cli生成的配置中的`client_type`字段名改成读时的`client`后如预期运行

**Comment by dongwlin** [comment]
看来是上次改错了（
