### ISSUE TITLE
Readme 链接错误

### ISSUE THREAD

**Issue by status102** [MaaAssistantArknights/MAA1999#36]
Readme中的链接无法链接到正确路径
[MaaFramework 的文档](https://github.com/MaaAssistantArknights/MaaFramework/blob/main/docs/zh_cn/3.3-%E4%BB%BB%E5%8A%A1%E6%B5%81%E6%B0%B4%E7%BA%BF%E5%8D%8F%E8%AE%AE.md)

**Comment by dongwlin** [comment]
玛丽给文档改名了，这边还没改（

**Comment by MistEO** [comment]
来个 PR （伸手

**Comment by status102** [comment]
![X%ZP3 U A~J}35QA$_`QZJF](https://github.com/MaaAssistantArknights/MAA1999/assets/102887808/0ce3ba98-cc99-400c-abe7-e9c3f75a4dfe)

歇逼（倒头就睡

**Comment by MistEO** [comment]
fixed
