### ISSUE TITLE
Bug: 新活动证明启示不自动执行

### ISSUE THREAD

**Issue by Bl1tzcrank** [MaaAssistantArknights/MAA1999#43]
模拟器：夜神
[maa.log](https://github.com/MaaAssistantArknights/MAA1999/files/13186220/maa.log)
具体在日志6477行左右。
在进入活动之后，在下图页面中选中关卡后就停止执行了，但在手动点击活动进入之后，又直接执行下一个收取任务奖励的任务。
![image](https://github.com/MaaAssistantArknights/MAA1999/assets/61381970/49784be1-607b-4222-85b8-a8cf92945139)

**Comment by Bl1tzcrank** [comment]
> 应该修好了~不过感觉pipeline还是非常不稳健~
> 
> 基于日志对成因的推测：正确进入活动主界面->识别`证明启示`（预期进入关卡列表）->连续识别成功两次，点击两次，第一次进了关卡列表，第二次恰好点到了`证明启示V`->在ROI内识别证明启示V->识别不到，一直识别卡死
> 
> 愿意的话，可以修改`config.json`中的调试选项至如下
> 
> ```js
> {
>     // ...
>     "debug": true,
>     // ...
> }
> ```
> 
> 这样会保留识别时的图像方便确认

今天用的时候把debug打开了，确实是您说的那个问题，连续点击两次导致识别不到。
但出现了另一个问题，应该也是类似的，就是每日的心相本是这样。第一次选中心相7后，第二次点击过快导致又返回到选择心相副本的界面，我附上几张图，如果还需要的话我可以把这些图都打包发上来。感谢您的回复。
以下是活动本的截图：
![ThePrisonerintheCaveTheProofs_2023 10 28-21 02 19 6609387](https://github.com/MaaAssistantArknights/MAA1999/assets/61381970/2f216b7e-8d85-457f-b99d-41aa1aefb2ea)
![ThePrisonerintheCaveTargetStageName_2023 10 28-21 02 19 8101678](https://github.com/MaaAssistantArknights/MAA1999/assets/61381970/33d33fb9-6543-4e5d-aa59-8a56bfcdcdb9)
![ThePrisonerintheCaveTheProofs_2023 10 28-21 02 20 6102574](https://github.com/MaaAssistantArknights/MAA1999/assets/61381970/2343674a-531c-4bef-986a-a53e20f01ede)

**Comment by Bl1tzcrank** [comment]
以下是每日心相本的截图：

![PsychubeStages_7_2023 10 28-21 00 04 5108877](https://github.com/MaaAssistantArknights/MAA1999/assets/61381970/0384a4a3-4323-4c0b-a2fe-2f2510c89443)
![PsychubeReadyForAction_2023 10 28-21 00 06 0782561](https://github.com/MaaAssistantArknights/MAA1999/assets/61381970/5b60ae26-9476-4fc0-bf3b-9842c7a17bdf)
![PsychubeStages_7_2023 10 28-21 00 06 1813621](https://github.com/MaaAssistantArknights/MAA1999/assets/61381970/f8e35dda-6e6d-4ed6-865c-a8ccdb7ec9c5)
![PsychubeReadyForAction_2023 10 28-21 00 07 6939531](https://github.com/MaaAssistantArknights/MAA1999/assets/61381970/638b6da3-4812-4d46-bb4f-798aeadd36ab)
![PsychubeStages_7_2023 10 28-21 00 07 7877151](https://github.com/MaaAssistantArknights/MAA1999/assets/61381970/a4266dd5-24d9-4a38-8863-008ca95761b9)

**Comment by Bl1tzcrank** [comment]
![FreePsychubeStages_2023 10 28-20 59 33 4140063](https://github.com/MaaAssistantArknights/MAA1999/assets/61381970/fa833e4c-343f-4b20-9ffe-84de444ee86c)
![PsychubeStages_7_2023 10 28-20 59 35 0350801](https://github.com/MaaAssistantArknights/MAA1999/assets/61381970/7b688e9d-e267-4146-a0a6-8ecc7cd09e0b)
![PsychubeReadyForAction_2023 10 28-20 59 35 1213338](https://github.com/MaaAssistantArknights/MAA1999/assets/61381970/9932ddab-dea7-4f25-9a91-1e03e6aaff61)
![PsychubeStages_7_2023 10 28-20 59 35 7906915](https://github.com/MaaAssistantArknights/MAA1999/assets/61381970/68e3065d-79df-4895-9238-cd261cb29027)
![PsychubeReadyForAction_2023 10 28-20 59 35 8849699](https://github.com/MaaAssistantArknights/MAA1999/assets/61381970/92f3f673-4922-48e2-9d5c-77770ce74104)

**Comment by Trust04zh** [comment]
@Bl1tzcrank 你后面提到的意志解析卡死的问题，我没一步一步分析原因，先在 #45 简单优化了下，看会不会好点，还有问题的话之后单开个新issue吧。
