### ISSUE TITLE
关于切换至行为复现的按钮的位置

### ISSUE THREAD

**Issue by Trust04zh** [MaaAssistantArknights/MAA1999#46]
SwitchToReplay的ROI有两个版本，看起来一个是老版本（没记错的话是1.3大版本更新前）复现按钮的位置（框框靠右的那张图），后来插入了一个切换成员队列的按钮，复现按钮的位置被挪到左边了。

那么现在还有关卡是复现按钮靠右的情况的吗？

![SwitchToReplay_2023 10 30-19 27 26 8211156](https://github.com/MaaAssistantArknights/MAA1999/assets/36195713/62938933-8d93-425d-8156-28d2b5689abd)
![SwitchToReplay_2023 10 30-19 27 26 7666466](https://github.com/MaaAssistantArknights/MAA1999/assets/36195713/f4cd31f8-9e96-454a-8ca4-cfc23f07f26e)

**Comment by MistEO** [comment]
兼容一下外服吧（确信
