### ISSUE TITLE
想请问一下mac系统应该如何使用maa1999

### ISSUE THREAD

**Issue by lindo146** [MaaAssistantArknights/MAA1999#47]
下载后发现并没有类似方舟脚本的那种dmg包，想知道如何操作操作才能使用？
看视频那个MAA1999_CLI文件打不开，好像说编码格式不行
![933c05d26b02c49872d73bac44b03340](https://github.com/MaaAssistantArknights/MAA1999/assets/115944231/5f4a03fd-915b-45bd-9312-73b6d13a2b06)
不知道要设置什么东西，希望有大佬解答一下，谢谢啦

**Comment by LiamSho** [comment]
https://www.bilibili.com/video/BV14E411J7n2/

**Comment by lindo146** [comment]
<img width="585" alt="image" src="https://github.com/MaaAssistantArknights/MAA1999/assets/115944231/94411fbb-ab1a-481e-a23e-5485bb9a6ef9">
更新一下情况，打开后寻找adb路径的时候报错了

**Comment by lindo146** [comment]
![c95567b5f73ef6b7e46770b7e9bc939f](https://github.com/MaaAssistantArknights/MAA1999/assets/115944231/f1200907-2565-4dec-ba68-8fbb7a212c88)
这个是输入的地址，adb地址是从方舟版maa日志中找的路径

**Comment by MistEO** [comment]
debug/maa.log 也发一下

**Comment by lindo146** [comment]
[maa.log](https://github.com/MaaAssistantArknights/MAA1999/files/13246316/maa.log)
补充文件

**Comment by MistEO** [comment]
mac 上似乎没法用别的程序的 adb，没法读，自己装一个试试
