### ISSUE TITLE
领每日活跃后，死循环（？），无法结束

### ISSUE THREAD

**Issue by dongwlin** [MaaAssistantArknights/MAA1999#8]
这是截取的日志
[1.log](https://github.com/MaaAssistantArknights/MAA1999/files/12123186/1.log)
日志中所有任务得分都低于阈值时仍在进行下一循环
![image](https://github.com/MaaAssistantArknights/MAA1999/assets/97545700/5175d1d8-70ca-4a98-aa65-444a6e3512fd)
这是卡死界面
![MuMu12-20230720-130502](https://github.com/MaaAssistantArknights/MAA1999/assets/97545700/152a5af2-fa35-4dac-bd8f-32e80260993c)

**Comment by dongwlin** [comment]
虽然日志是20号的，但是今天21号也有遇到这种情况，而且日志内容也是相同的

**Comment by MistEO** [comment]
v0.1.4 fixed
